<?php
	session_start();
	// Inclui a conexão
	include_once("seguranca.php");

	if($_SESSION['email'] != ""){
		include_once("connect.php");
	}

	// Nome do Arquivo do Excel que será gerado
	$arquivo = 'dadosmusicanaescola.xls';

	// Criamos uma tabela HTML com o formato da planilha para excel
	$tabela = '<table border="1">';
	$tabela .= '<tr>';
	$tabela .= '<td colspan="2">Dados Questionário</td>';
	$tabela .= '</tr>';
	$tabela .= '<tr>';
	$tabela .= '<td><b>Id</b></td>';
	$tabela .= '<td><b>Escola</b></td>';
	$tabela .= '<td><b>Cidade</b></td>';
	$tabela .= '<td><b>Data</b></td>';
	$tabela .= '<td><b>q1</b></td>';
	$tabela .= '<td><b>q2</b></td>';
	$tabela .= '<td><b>q2_outros</b></td>';
	$tabela .= '<td><b>q3</b></td>';
	$tabela .= '<td><b>q4</b></td>';
	$tabela .= '<td><b>q5</b></td>';
	$tabela .= '<td><b>q5_1</b></td>';
	$tabela .= '<td><b>q5_2</b></td>';
	$tabela .= '<td><b>q5_2_outros</b></td>';
	$tabela .= '<td><b>q6</b></td>';
	$tabela .= '<td><b>q6_1</b></td>';
	$tabela .= '<td><b>q7</b></td>';
	$tabela .= '<td><b>q7_1</b></td>';
	$tabela .= '<td><b>q7_2</b></td>';
	$tabela .= '<td><b>q8</b></td>';
	$tabela .= '<td><b>q8_1</b></td>';
	$tabela .= '<td><b>q9_1a</b></td>';
	$tabela .= '<td><b>q9_1b</b></td>';
	$tabela .= '<td><b>q9_1c</b></td>';
	$tabela .= '<td><b>q9_2a</b></td>';
	$tabela .= '<td><b>q9_2b</b></td>';
	$tabela .= '<td><b>q9_2c</b></td>';
	$tabela .= '<td><b>q9_3a</b></td>';
	$tabela .= '<td><b>q9_3b</b></td>';
	$tabela .= '<td><b>q9_3c</b></td>';
	$tabela .= '<td><b>q9_4a</b></td>';
	$tabela .= '<td><b>q9_4b</b></td>';
	$tabela .= '<td><b>q9_4c</b></td>';
	$tabela .= '<td><b>q9_5a</b></td>';
	$tabela .= '<td><b>q9_5b</b></td>';
	$tabela .= '<td><b>q9_5c</b></td>';
	$tabela .= '<td><b>q9_6a</b></td>';
	$tabela .= '<td><b>q9_6b</b></td>';
	$tabela .= '<td><b>q9_6c</b></td>';
	$tabela .= '<td><b>q9_complemento</b></td>';
	$tabela .= '<td><b>q10_1a</b></td>';
	$tabela .= '<td><b>q10_1b</b></td>';
	$tabela .= '<td><b>q10_2a</b></td>';
	$tabela .= '<td><b>q10_2b</b></td>';
	$tabela .= '<td><b>q10_2c</b></td>';
	$tabela .= '<td><b>q10_3a</b></td>';
	$tabela .= '<td><b>q10_3b</b></td>';
	$tabela .= '<td><b>q10_4a</b></td>';
	$tabela .= '<td><b>q10_4b</b></td>';
	$tabela .= '<td><b>q10_4c</b></td>';
	$tabela .= '<td><b>q10_5a</b></td>';
	$tabela .= '<td><b>q10_5b</b></td>';
	$tabela .= '<td><b>q10_5c</b></td>';
	$tabela .= '<td><b>q10_6a</b></td>';
	$tabela .= '<td><b>q10_6b</b></td>';
	$tabela .= '<td><b>q10_6c</b></td>';
	$tabela .= '<td><b>q10_7a</b></td>';
	$tabela .= '<td><b>q10_7b</b></td>';
	$tabela .= '<td><b>q10_7c</b></td>';
	$tabela .= '<td><b>q10_8a</b></td>';
	$tabela .= '<td><b>q10_8b</b></td>';
	$tabela .= '<td><b>q10_8c</b></td>';
	$tabela .= '<td><b>q10_9a</b></td>';
	$tabela .= '<td><b>q10_9b</b></td>';
	$tabela .= '<td><b>q10_9c</b></td>';
	$tabela .= '<td><b>q10_10a</b></td>';
	$tabela .= '<td><b>q10_10b</b></td>';
	$tabela .= '<td><b>q10_10c</b></td>';
	$tabela .= '<td><b>q10_11a</b></td>';
	$tabela .= '<td><b>q10_11b</b></td>';
	$tabela .= '<td><b>q10_11c</b></td>';
	$tabela .= '<td><b>q10_12a</b></td>';
	$tabela .= '<td><b>q10_12b</b></td>';
	$tabela .= '<td><b>q10_12c</b></td>';
	$tabela .= '<td><b>q10_complemento</b></td>';
	$tabela .= '<td><b>q11</b></td>';
	$tabela .= '<td><b>q11_1</b></td>';
	$tabela .= '<td><b>q12</b></td>';
	$tabela .= '<td><b>q12_1</b></td>';
	$tabela .= '</tr>';

	// Puxando dados do Banco de dados	
	$resultado = $conexao->query("SELECT * FROM questionario");

	while($row = $resultado->fetch_object()){	
		$tabela .= '<tr>';
		$tabela .= '<td>'.$row->id.'</td>';
		$tabela .= '<td>'.$row->escola.'</td>';
		$tabela .= '<td>'.$row->cidade.'</td>';
		$tabela .= '<td>'.$row->data.'</td>';
		$tabela .= '<td>'.$row->q1.'</td>';
		$tabela .= '<td>'.$row->q2.'</td>';
		$tabela .= '<td>'.$row->q2_outros.'</td>';
		$tabela .= '<td>'.$row->q3.'</td>';
		$tabela .= '<td>'.$row->q4.'</td>';
		$tabela .= '<td>'.$row->q5.'</td>';
		$tabela .= '<td>'.$row->q5_1.'</td>';
		$tabela .= '<td>'.$row->q5_2.'</td>';
		$tabela .= '<td>'.$row->q5_2_outros.'</td>';
		$tabela .= '<td>'.$row->q6.'</td>';
		$tabela .= '<td>'.$row->q6_1.'</td>';
		$tabela .= '<td>'.$row->q7.'</td>';
		$tabela .= '<td>'.$row->q7_1.'</td>';
		$tabela .= '<td>'.$row->q7_2.'</td>';
		$tabela .= '<td>'.$row->q8.'</td>';
		$tabela .= '<td>'.$row->q8_1.'</td>';
		$tabela .= '<td>'.$row->q9_1a.'</td>';
		$tabela .= '<td>'.$row->q9_1b.'</td>';
		$tabela .= '<td>'.$row->q9_1c.'</td>';
		$tabela .= '<td>'.$row->q9_2a.'</td>';
		$tabela .= '<td>'.$row->q9_2b.'</td>';
		$tabela .= '<td>'.$row->q9_2c.'</td>';
		$tabela .= '<td>'.$row->q9_3a.'</td>';
		$tabela .= '<td>'.$row->q9_3b.'</td>';
		$tabela .= '<td>'.$row->q9_3c.'</td>';
		$tabela .= '<td>'.$row->q9_4a.'</td>';
		$tabela .= '<td>'.$row->q9_4b.'</td>';
		$tabela .= '<td>'.$row->q9_4c.'</td>';
		$tabela .= '<td>'.$row->q9_5a.'</td>';
		$tabela .= '<td>'.$row->q9_5b.'</td>';
		$tabela .= '<td>'.$row->q9_5c.'</td>';
		$tabela .= '<td>'.$row->q9_6a.'</td>';
		$tabela .= '<td>'.$row->q9_6b.'</td>';
		$tabela .= '<td>'.$row->q9_6c.'</td>';
		$tabela .= '<td>'.$row->q9_complemento.'</td>';
		$tabela .= '<td>'.$row->q10_1a.'</td>';
		$tabela .= '<td>'.$row->q10_1b.'</td>';
		$tabela .= '<td>'.$row->q10_2a.'</td>';
		$tabela .= '<td>'.$row->q10_2b.'</td>';
		$tabela .= '<td>'.$row->q10_2c.'</td>';
		$tabela .= '<td>'.$row->q10_3a.'</td>';
		$tabela .= '<td>'.$row->q10_3b.'</td>';
		$tabela .= '<td>'.$row->q10_4a.'</td>';
		$tabela .= '<td>'.$row->q10_4b.'</td>';
		$tabela .= '<td>'.$row->q10_4c.'</td>';
		$tabela .= '<td>'.$row->q10_5a.'</td>';
		$tabela .= '<td>'.$row->q10_5b.'</td>';
		$tabela .= '<td>'.$row->q10_5c.'</td>';
		$tabela .= '<td>'.$row->q10_6a.'</td>';
		$tabela .= '<td>'.$row->q10_6b.'</td>';
		$tabela .= '<td>'.$row->q10_6c.'</td>';
		$tabela .= '<td>'.$row->q10_7a.'</td>';
		$tabela .= '<td>'.$row->q10_7b.'</td>';
		$tabela .= '<td>'.$row->q10_7c.'</td>';
		$tabela .= '<td>'.$row->q10_8a.'</td>';
		$tabela .= '<td>'.$row->q10_8b.'</td>';
		$tabela .= '<td>'.$row->q10_8c.'</td>';
		$tabela .= '<td>'.$row->q10_9a.'</td>';
		$tabela .= '<td>'.$row->q10_9b.'</td>';
		$tabela .= '<td>'.$row->q10_9c.'</td>';
		$tabela .= '<td>'.$row->q10_10a.'</td>';
		$tabela .= '<td>'.$row->q10_10b.'</td>';
		$tabela .= '<td>'.$row->q10_10c.'</td>';
		$tabela .= '<td>'.$row->q10_11a.'</td>';
		$tabela .= '<td>'.$row->q10_11b.'</td>';
		$tabela .= '<td>'.$row->q10_11c.'</td>';
		$tabela .= '<td>'.$row->q10_12a.'</td>';
		$tabela .= '<td>'.$row->q10_12b.'</td>';
		$tabela .= '<td>'.$row->q10_12c.'</td>';
		$tabela .= '<td>'.$row->q10_complemento.'</td>';
		$tabela .= '<td>'.$row->q11.'</td>';
		$tabela .= '<td>'.$row->q11_1.'</td>';
		$tabela .= '<td>'.$row->q12.'</td>';
		$tabela .= '<td>'.$row->q12_1.'</td>';		
		$tabela .= '</tr>';
	}

	$tabela .= '</table>';

	// Força o Download do Arquivo Gerado
	header ('Cache-Control: no-cache, must-revalidate');
	header ('Pragma: no-cache');
	header('Content-Type: application/x-msexcel');
	header ("Content-Disposition: attachment; filename=\"{$arquivo}\"");
	echo $tabela;
?>